### ISSUE TITLE
version mismatch between tag and shard

### ISSUE THREAD

**Issue by maiha** [taylorfinnell/awscr-signer#53]
current `v0.8.0` tag points to `0.7.0` of shard.yml.

```console
$ git show v0.8.0:shard.yml | grep version
version: 0.7.0
```

This forces `shards build` to fetch repository always.

```console
Fetching https://github.com/taylorfinnell/awscr-signer.git
Installing awscr-signer (0.7.0 at 0.8.0)
```

Could you re-tag to `f5fd505` or create a new tag `v0.8.1` to current master?

**Comment by taylorfinnell** [comment]
Release v0.8.1, sorry about that

**Comment by maiha** [comment]
Thanks for the quick response!
