### ISSUE TITLE
Release new version to support newer crystal

### ISSUE THREAD

**Issue by veelenga** [taylorfinnell/awscr-signer#58]
awscr-s3 points to awscr-signer@v0.8.1, which does not satisfy the crystal 1.0.0 compatibility. See for details:

https://github.com/crystal-community/timecop.cr/pull/7#issuecomment-815505128

Actions to be taken:

* release latest awscr-signer
* release awscr-s3 pointing to the latest awscr-signer in shard.yml

**Comment by taylorfinnell** [comment]
Is the new way of specifying the Crystal version (`crystal: ">= ..."`) backwards compat with older crystal/shards version? Not sure how I should bump the version here

**Comment by taylorfinnell** [comment]
Actually (I didn't test it) but I doubt this shard even works with `0.31.0`. Maybe I will just bump to 1.0.0 and make min crystal 1.0.0 too

**Comment by veelenga** [comment]
The version is already bumped in master (but not released):

https://github.com/taylorfinnell/awscr-signer/blob/bfe03aa4235e67fa4926c74eda3a1a64404bd111/shard.yml#L3

I pointed awscr-s3 to awscr-singer@master and it started to work. So I assume no changes needed in this repo, just a new release.

**Comment by taylorfinnell** [comment]
Oh right, thanks!
